name: Create Release

on:
  push:
    branches:
      - main

jobs:
  create_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Git Config
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Create Tag
        run: git tag v1.0.1

      - name: Push Tag
        run: git push origin v1.0.1

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: v1.0.1
          release_name: Release v1.0.1
          body: |
            Release notes for v1.0.1
          draft: false
          prerelease: false

      - name: Get Release URL
        run: echo "Release URL: "
